---

- hosts: all
  tasks:

    - name: Install podman
      package:
        name: podman
        state: present

    - name: Download some podman containers
      command: podman pull "{{ item }}"
      with_items:
        - "fedora:29"
        - "centos:7"
        - "alpine:latest"

    - name: Run a command in a container
      command: "podman run --rm centos:7 rpm -qa"
