---

- hosts: all
  tasks:

    - name: Install podman
      package:
        name: podman
        state: present

    - name: Download some podman containers
      command: podman pull "{{ item }}"
      with_items:
        - "fedora:29"
        - "centos:7"
        - "alpine:latest"
