---

- hosts: all
  vars:
    required_packages:
      - automake
      - "@Development Tools"
      - libacl
      - libacl-devel
      - libaio
      - libaio-devel
      - libntirpc-devel
      - lksctp-tools-devel
      - numactl-devel
      - numactl-libs
      - xfsprogs
      - xfsprogs-devel
      - uClibc-devel
  tasks:

    - name: Install requirements
      package:
        name: "{{ required_packages }}"
        state: present

    - name: Clone LTP
      git:
        repo: https://github.com/linux-test-project/ltp
        dest: /opt/ltp
        version: 20190115
        update: no
        depth: 5

    - name: Compile LTP
      command: "{{ item }}"
      args:
        chdir: /opt/ltp
      with_items:
        - "make -j{{ ansible_processor_vcpus }} autotools"
        - "./configure"
        - "make -j{{ ansible_processor_vcpus }}"
        - make install

    - name: Run LTP
      command: /opt/ltp/runltp
      args:
        chdir: /opt/ltp
      async: 1800
      poll: 0
      register: ltp_run

    - name: Check if LTP run has completed
      async_status:
        jid: "{{ ltp_run.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 1800
