---

- hosts: all
  vars:
    required_packages:
      - "@Development Tools"
  tasks:

    - name: Install requirements
      package:
        name: "{{ required_packages }}"
        state: present

    - name: Clone LTP
      git:
        repo: https://github.com/linux-test-project/ltp
        dest: /opt/ltp
        version: 20190115
        clone: yes
        update: yes

    - name: Compile LTP
      command: "{{ item }}"
      args:
        chdir: /opt/ltp
      with_items:
        - make autotools
        - "./configure"
        - make
        - make install

    - name: Run LTP
      command: /opt/ltp/runltp
      args:
        chdir: /opt/ltp
